version: '3.8'
services:
  frontend:
    image: auction-frontend:latest
    build:
      context: .
      dockerfile: apps/auction-frontend/Dockerfile
    ports:
      - '8080:80'
    environment:
      - AUCTION_API_URL=http://auction-service:3000
      - BIDDING_API_URL=http://bidding-service:3001
      - PAYMENT_API_URL=http://payment-service:3002
    networks:
      - auction-network
  auction-service:
    image: auction-service:latest
    build:
      context: .
      dockerfile: apps/auction-service/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=auction_db
    depends_on:
      - mysql
    networks:
      - auction-network
  bidding-service:
    image: bidding-service:latest
    build:
      context: .
      dockerfile: apps/bidding-service/Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - PUBSUB_PROJECT_ID=your-gcp-project
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=auction_db
    depends_on:
      - redis
      - mysql
    networks:
      - auction-network
  payment-service:
    image: payment-service:latest
    build:
      context: .
      dockerfile: apps/payment-service/Dockerfile
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=production
      - STRIPE_SECRET_KEY=your_stripe_secret_key
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=auction_db
    depends_on:
      - mysql
    networks:
      - auction-network
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=auction_db
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - auction-network
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - auction-network
networks:
  auction-network:
    driver: bridge
volumes:
  mysql-data:
